### ISSUE TITLE
cleanup file has Windows line endings

### ISSUE THREAD

**Issue by bgoodri** [artemis-toumazi/dfpk#3]
The `cleanup` file in dfpk has Windows line endings (\r), which causes it to not execute correctly on non-Windows computers. This is what caused the Models.hpp file to not be rebuilt after the `fmax` issues were fixed, so it is still failing to build sometimes
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/dfpk-00install.html
GitHub is not allowing me to upload the fixed file, but let me know if you have trouble converting the line endings. With that, dfpk seems to build correctly on my computer.

**Comment by artemis-toumazi** [comment]
Hello,

Thanks for noticing this and letting me know. I am sorry it took that long to respond.
I've just pushed a commit fixing line endings using the dos2unix command. 
Would you be able to try this on your computer since i don't own a Linux computer to try this myself? I would then be able to upload a new version.

**Comment by bgoodri** [comment]
Passes R CMD check on Linux with just a note about the LICENSE file.

**Comment by artemis-toumazi** [comment]
I ve just uploaded a new version with the latest fixes. i ll close the issue here since it looks like it is fixed. Thank you for your help once again.
